
networks:
  rustdesk-net:
    #external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    build: .
    command: hbbs
    volumes:
      - ./data:/root:z
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
    environment:
      # Only allow logged-in users to control other systems: Y/N
      LOGGED_IN_ONLY: N
      # Always use the relay, even within the same subnet: Y/N
      ALWAYS_USE_RELAY: N
      # Enforce access checks (requires the API server!): Y/N/T
      # (T=Test; check permissions and log result, but always grant anyway)
      ENFORCE_ACCESS_CHECKS: T
      # Adress of API server for checking logged-in status and access permissions
      # Example: https://rustdesk.domain.example/
      API_SERVER: ${API_SERVER}
    logging:
      driver: journald
      options:
        tag: docker/rustdesk-hbbs

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    build: .
    command: hbbr
    volumes:
      - ./data:/root:z
    networks:
      - rustdesk-net
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: docker/rustdesk-hbbr

