
networks:
  rustdesk-net:
    #external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    build: .
    command: hbbs
    volumes:
      - ./data:/root:z
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
    environment:
      LOGGED_IN_ONLY: N
      ALWAYS_USE_RELAY: N
      ENFORCE_ACCESS_CHECKS: T
      API_SERVER: ${API_SERVER}
    logging:
      driver: journald
      options:
        tag: docker/rustdesk-hbbs

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    build: .
    command: hbbr
    volumes:
      - ./data:/root:z
    networks:
      - rustdesk-net
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: docker/rustdesk-hbbr

