# Combined server for RustDesk API Server and its backend
# ATTENTION: Webservices will only work if httpS is added; you should do this anyway for security. Use e.g LetsEncrypt!
server {
    server_tokens off;
    server_name $SERVER-DOMAIN-NAME$;
    root /var/www/rustdesk;

    # TODO: CHECK & TEST
    listen 21114 ssl http2 fastopen=500;
    #listen 443 ssl http2 fastopen=500;

    # Create nonce for CSP for scripts and CSS
    set $cspNonce $request_id;
    # Replace placesholder in index.html
    sub_filter_once off;
    sub_filter CSP_NONCE $cspNonce;

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'nonce-$cspNonce'; style-src 'nonce-$cspNonce' 'self'; media-src 'self' data:; font-src 'self'; trusted-types angular angular#bundler default dompurify; require-trusted-types-for 'script'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; worker-src 'self' blob:; img-src 'self' data:; upgrade-insecure-requests; connect-src 'self' https://tiles.openfreemap.org/";
    # img-src: 'data:' needed by MapLibre to load map data; same for connect-src URL (map tiles)
    # worker-src: 'blob:' needed for map script
    if ($request_method !~ ^(GET|HEAD|POST|DELETE|PATCH)$) {
        return 405;
    }

    # Block as additional security
    location ~ /\. {
        return 444;
    }

    # / for web frontend (and /webapi for web backend; and /api for RustDesk API)
    location / {
        proxy_pass http://127.0.0.1:21114/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 20s;
        # Need high burst for automatic calls to backend
        limit_req zone=backend_zone burst=50 nodelay;
    }

    location /ws/id {
        proxy_pass http://127.0.0.1:21118;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        limit_req zone=backend_zone burst=10 nodelay;
    }

    location /ws/relay {
        proxy_pass http://127.0.0.1:21119;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        limit_req zone=backend_zone burst=10 nodelay;
    }

}
